### ISSUE TITLE
Merge oioioi and szkopuł repositories

### ISSUE THREAD

**Issue by edokimok** [sio2project/oioioi#155]
# Tasks overview
- [ ] move and adjust commits specific to szkopuł to oioioi repository
  - [x] pick ready-to-merge commit IDs
  - [x] pick commit IDs to delete
  - [ ] adjust rest of commits to fit oioioi repo

### *List of commits on szkopuł only*

- [x] * f64b36aa (HEAD -> master, origin/master, origin/HEAD) dodanie brakującego pliku
- [x] * 08d1a92b add "Projekt MAP" banner
- [x] * 78228e3c Add link to Szkopuł kursy page.
- [x] * 83d76b24 HOTFIX for duplicates in contest ranking (by Alicja Kluczek)
- [ ] * f4d0312a PRODFIX set c++17 for non-makefile sinol packages
- [x] * d268e04d (temporary) Allow lorys to manage packages inside his contest
- [ ] * d46ffb64 (to-master) usercontests should not be public
- [x] * f08f0a88 [tmp] instrument The Queries for perf measure
- [ ] * 3f55b321 [PRODFIX] Change oioioi/notifications/server/npm-shrinkwrap.json
- [x] * d1302cc7 Added Main importer
- [x] * 6fd48ce5 [TEMPFIX] Print where the empty controller hack is needed
- [x] * 8a099a68 TEMPFIX
- [ ] * d7585118 TMPHACK
- [x] * d65532b0 [DEBUG] Added more workers debug
- [x] * 07d0d491 [DEBUG][IMPORTANT] Add some debug messages to receive_from_workers
- [ ] * 0954e73e Uncommited changes
- [x] * 37ba2091 [HOTFIX] Some localchanges to sharingcli on Szkopuł
- [x] * 36d0433d [HOTFIX] Remove oi dependency from participants migration

**Comment by etiaro** [comment]
# determine how to make new settings safe

Move as much of settings.py into basic_settings.py
Move all szkopuł-specific settings into szkopul_settings.py (without configs like filetracker,sentry,db, etc.)

In effect make settings.py as short as possible

**Comment by sommbre** [comment]
Commits ready to merge:
* 83d76b2 HOTFIX for duplicates in contest ranking (by Alicja Kluczek)

Commits to be entirely deleted from szkopuł:
* 6fd48ce [TEMPFIX] Print where the empty controller hack is needed
* d65532b [DEBUG] Added more workers debug
* 07d0d49 [DEBUG][IMPORTANT] Add some debug messages to receive_from_workers

I'm also not sure about f08f0a8 [tmp] instrument The Queries for perf measure because of:
1. It's marked as a temporary commit
2. It adds a few elasticapm spans to catch some requests and monitor them. However, elastic is only used in this one place and it doesn't seem to be a full-blown monitoring setup but rather a simple check
3. It was created 3 years ago, unless this commit actually introduces monitoring that someone is using regularly, this addition is probably long forgotten

From my perspective, it can also be deleted but I need a second opinion on that one.

**Comment by DietPawel** [comment]
Change https://github.com/sio2project/oioioi/commit/d268e04dc80911893cff8684a6aad488441a2b02 (temporary) Allow lorys to manage packages inside his contest can be omitted and removed

**Comment by sommbre** [comment]
Following commits can be reverted when #189 and [#1](https://github.com/sio2project/oioioi-contrib/pull/1) are merged
- d1302cc7 Added Main importer
- 37ba2091 [HOTFIX] Some localchanges to sharingcli on Szkopuł

**Comment by etiaro** [comment]
Without this commit it's impossible to create even empty database on settings from szkopul

[[HOTFIX] Remove oi dependency from participants migration](https://github.com/sio2project/oioioi/commit/36d0433dfb84e6cb0a57f7133ba84ee7370d724c)

**Comment by sommbre** [comment]
3f55b321 [PRODFIX] Change oioioi/notifications/server/npm-shrinkwrap.json can be reverted once #195 is merged and deployed

**Comment by sommbre** [comment]
The following commits are included in #197 as is:
- [ ] f64b36aa dodanie brakującego pliku
- [ ] 78228e3c Add link to Szkopuł kursy page.

08d1a92b add "Projekt MAP" banner should be reverted as original commit included manually changed .po files.

**Comment by twalen** [comment]
sharingcli module has been removed from INSTALLED_APPS (in szkopuł settings)

**Comment by kama-pa-go** [comment]
This issue was moved to the "done" category in 2023.
All differences between oioioi and szkopuł were resolved in some way.

Relate to #586
