### ISSUE TITLE
Display contest rules 

### ISSUE THREAD

**Issue by Kostero** [sio2project/oioioi#171]
Add a subpage explaining the contest rules. This should be created automatically from the contest controller, for example:

* You will be able to see your score after each submission.
* For each problem, the submission with the maximum number of points is taken into account in the scoreboard.
* You score will be penalized if your submission exceeds half the time limit.

**Comment by NadiaHoffmann** [comment]
### Tasks overview:
- [ ] Search where to add the method for generating the HTML content
- [ ] Check if there is no function for getting the contest rules from ContestController yet
- [ ] Search for all useful functions that may help in generating the contest rules
- [ ] Find a way to make strings out of the rules 
- [ ] Add a method for making a list of the rules
- [ ] Write tests for a list of rules
- [ ] Create dashboard-rules.html
